templates_path: templates

github:
  org: mishudark
  repo: api-autogen

common: [bolt]
pkg_client: moon

components:
- package: color
  struct_type: Color
  source_struct: types.go
- package: manufacturer
  struct_type: Manufacturer
  source_struct: types.go
